ecommerce/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'ecommerce'  # This will be like this: {% url 'ecommerce:detail' item.id %} on our templates.
urlpatterns = [
                  url(r'^$', views.index, name='index'),
                  url(r'^products/$', views.products, name='products'),
                  url(r'^product/(?P<product_id>[0-9]+)/$', views.single_product, name='single_product'),
                  url(r'^about/$', views.about, name='about'),
                  url(r'^contact/$', views.contact, name='contact'),
                  url(r'^cart/$', views.cart, name='cart'),
                  url(r'^checkout/$', views.checkout, name='checkout'),
                  url(r'^payment-paypal$', views.payment_paypal, name='payment-paypal'),
                  url(r'^cash-on-delivery$', views.checkout_cash_on_delivery, name='checkout-cash-on-delivery'),
                  url(r'^cash-on-delivery/order/created/$', views.cash_on_delivery_order_created,
                      name='cash_on_delivery_created'),
                  url(r'^checkout/paypal$', views.checkout_paypal, name='paypal-checkout'),
                  url(r'^checkout/payment/process/$', views.proceed_to_pay, name='proceed-to-pay'),
                  url(r'^search/$', views.product_search, name='search'),

                  url(r'^user/', include([
                      url(r'^login/$', views.user_login, name='user_login'),
                      url(r'^register/$', views.user_register, name='user_register'),
                      url(r'^account/$', views.user_account, name='user_account'),
                      url(r'^products/$', views.user_products, name='user_products'),
                      url(r'^product/create/$', views.user_product_create, name='user_product_create'),
                      url(r'^product/update/(?P<product_id>[0-9]+)/$', views.user_product_update,
                          name='user_product_update'),
                      url(r'^product/update/set-featured-image/', views.set_featured_image),
                      url(r'^product/update/unset-image/$', views.unset_image),
                      url(r'^product/unset-product/$', views.unset_product),
                      url(r'^logout/$', views.logout),
                  ])),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insight/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = i18n_patterns(
        url(r'^ecommerce/', include('ecommerce.urls')),  # Include ecommerce app views.
        url(r'^admin/', admin.site.urls),

)

ecommerce/models.py
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save, pre_save


class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(verbose_name=_("Phone Number"), max_length=30)
    about = models.TextField(verbose_name=_("About"))

    class Meta:
        verbose_name = _("Member")
        verbose_name_plural = _("Members")


class Product(models.Model):
    name = models.CharField(verbose_name=_("Name"), max_length=200)
    content = models.TextField(verbose_name=_("Content"))
    excerpt = models.TextField(verbose_name=_("Excerpt"))
    price = models.DecimalField(verbose_name=_("Price"), max_digits=20, decimal_places=2)
    status = models.IntegerField(verbose_name=_("Status"), default=0)
    date = models.DateTimeField(verbose_name=_("Date"), auto_now_add=True)
    quantity = models.PositiveIntegerField(verbose_name=_("Quantity"))
    author = models.PositiveIntegerField(verbose_name=_("Author"))
    featured_image = models.CharField(verbose_name=_("Featured_image"), max_length=300)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    product_location = '/ar/ecommerce/media/products/' + str(instance.product.id)
    fs = FileSystemStorage(location=product_location)
    uploaded_file_url = product_location + '/' + filename
    return uploaded_file_url


class Image(models.Model):
    product = models.ForeignKey(Product, verbose_name=_("Product"), on_delete=models.CASCADE)
    image = models.ImageField(verbose_name=_("Image"))

    class Meta:
        verbose_name = _("Image")
        verbose_name_plural = _("Images")

# def save(self, *args, **kwargs):
#     product_location = 'media/products/' + str(instance.product.id)
#     fs = FileSystemStorage(location=product_location)
#     uploaded_file_url = product_location + '/' + filename
#     return uploaded_file_url
#
#
#     p = Product.objects.get(id=self.product.id)
#
#     p.featured_image = "products/{0}/{1}".format(p.id, self.image)
#     p.save()
#     super(Image, self).save(*args, **kwargs)


# @receiver(post_save, sender=Image)
# def save_image(sender, instance, **kwargs):
#     instance.product.featured_image = instance.image
#     instance.save()
#
#     #instance.product.featured_image = kwargs['image']
#     #instance.save()
#

ecommerce/views.py
import os
import re
from time import gmtime, strftime

import braintree
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, \
    login  # Use alias like "django_logout" so that django doesnt get confused on which function to use.
from django.contrib.humanize.templatetags.humanize import intcomma
from django.core.files.storage import FileSystemStorage
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.template.defaulttags import register
from django.views.decorators.csrf import csrf_exempt

from orders.forms import OrderCreateForm
from orders.models import Order, OrderItem
from .apps import EcommerceConfig
from .forms import *
from .helpers import Helpers
from .models import Member, Product, Image, User

paypal_access_token = "access_token$sandbox$8f9htcykq255v55n$d8e95f2daddb1d62da6199d05352bb4a"


def index(request):
    preview_products = Product.objects.all().order_by('-id')[:12]

    return render(request, Helpers.get_url('index.html'),
                  {'products': preview_products, 'currency': EcommerceConfig.currency})


def single_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    author = get_object_or_404(User, pk=product.author)
    product_images = product.image_set.all()
    images = []
    cart_items = request.session

    # Create an empty cart object if it does not exist yet
    if not cart_items.has_key("cart"):
        cart_items["cart"] = {}

    in_cart = True if cart_items['cart'].get(str(product_id)) else False

    if product_images:
        for data in product_images:
            images.append({"small": Helpers.get_path(str(data.image)), 'big': Helpers.get_path(str(data.image))})

    return render(request, Helpers.get_url('product/single.html'),
                  {'product': product, 'images': str(images).replace("'", '"'), 'in_cart': in_cart, 'author': author,
                   'currency': EcommerceConfig.currency})


def products(request):
    if request.method == 'POST':
        pagination_content = ""
        page_number = request.POST['data[page]'] if request.POST['data[page]'] else 1
        page = int(page_number)
        name = request.POST['data[name]']
        sort = '-' if request.POST['data[sort]'] == 'DESC' else ''
        search = request.POST['data[search]']
        max = int(request.POST['data[max]'])

        cur_page = page
        page -= 1
        per_page = max  # Set the number of results to display
        start = page * per_page

        # If search keyword is not empty, we include a query for searching
        # the "content" or "name" fields in the database for any matched strings.
        if search:
            all_posts = Product.objects.filter(Q(content__contains=search) | Q(name__contains=search)).exclude(
                status=0).order_by(sort + name)[start:per_page]
            count = Product.objects.filter(Q(content__contains=search) | Q(name__contains=search)).exclude(
                status=0).count()

        else:
            all_posts = Product.objects.exclude(status=0).order_by(sort + name)[start:cur_page * max]
            count = Product.objects.exclude(status=0).count()

    else:
        return render(request, 'ecommerce/product/index.html')


def product_search(request):
    queryset_list = Product.objects.order_by('-date')
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(excerpt__icontains=keywords)
    if 'price' in request.GET:
        price = request.GET['price']
        queryset_list = queryset_list.filter(price__icontains=price)

    context = {
        'products': queryset_list,
        'values': request.GET
    }
    return render(request, Helpers.get_url('product/search.html'), context)


def about(request):
    return render(request, Helpers.get_url('about.html'))


def contact(request):
    return render(request, Helpers.get_url('contact.html'))


def paymentDetails(request):
    return render(request, Helpers.get_url('payment-details.html'))


def user_login(request):
    # Redirect if already logged-in
    if request.user.is_authenticated:
        return HttpResponseRedirect(Helpers.get_path('user/account'))

    if request.method == 'POST':
        # Process the request if posted data are available
        username = request.POST['username']
        password = request.POST['password']
        # Check username and password combination if correct
        user = authenticate(username=username, password=password)
        if user is not None:
            # Success, now let's login the user.
            login(request, user)
            # Then redirect to the accounts page.
            return HttpResponseRedirect(Helpers.get_path('user/account'))
        else:
            # Incorrect credentials, let's throw an error to the screen.
            return render(request, Helpers.get_url('user/login.html'),
                          {'error_message': 'Incorrect username and / or password.'})
    else:
        # No post data availabe, let's just show the page to the user.
        return render(request, Helpers.get_url('user/login.html'))


def user_account(request):
    err_succ = {'status': 0, 'message': 'An unknown error occured'}

    # Create instance of the form and populate it with requests
    form = AccountForm(request.POST)

    # Redirect if not logged-in
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(Helpers.get_path('user/login'))

    if request.method == 'POST':
        if form.is_valid():
            # Query data of currently logged-in user.
            user = User.objects.get(username=request.user.username)

            # Check if username exists
            if User.objects.filter(username=form.cleaned_data['username']).exists() and user.username != \
                    form.cleaned_data['username']:
                err_succ['message'] = 'Username aleady taken, please enter a different one.'

            # Check if email exists
            elif User.objects.filter(email=form.cleaned_data['email']).exists() and user.email != form.cleaned_data[
                'email']:
                err_succ['message'] = 'Email already taken, please enter a different one'

            elif form.cleaned_data['old_password'] and form.cleaned_data['password_repeat'] and form.cleaned_data[
                'password']:
                # Check if passwords match
                if form.cleaned_data['password_repeat'] != form.cleaned_data['password']:
                    err_succ['message'] = 'New password do not match.'

                # Check if old password is correct
                elif not user.check_password(form.cleaned_data['old_password']):
                    err_succ['message'] = 'Incorrect old password.'

            else:
                user.username = form.cleaned_data['username']
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']

                user.member.phone_number = form.cleaned_data['phone_number']
                user.member.about = form.cleaned_data['about_me']

                # Save new password if passes above validations
                if form.cleaned_data['password']:
                    user.set_password(form.cleaned_data['password'])

                # Save posted fields to their respective tables
                user.member.save()
                user.save()

                # Show success message
                err_succ['status'] = 1
                err_succ['message'] = 'Account successfully updated.'

        return JsonResponse(err_succ)
    else:
        # Let's define intial data that we are going to use to popul
        # ate our account form.
        user_data = {
            'username': request.user.username,
            'email': request.user.email,
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'phone_number': request.user.member.phone_number,
            'about_me': request.user.member.about
        }
        # Render the account form
        return render(request, Helpers.get_url('user/account.html'), {'form': AccountForm(initial=user_data)})


def user_products(request):
    # Redirect if not logged-in
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(Helpers.get_path('user/login'))

    if request.method == 'POST':
        pagination_content = ""
        page_number = request.POST['data[page]'] if request.POST['data[page]'] else 1
        page = int(page_number)
        name = request.POST['data[th_name]']
        sort = '-' if request.POST['data[th_sort]'] == 'DESC' else ''
        search = request.POST['data[search]']
        max = int(request.POST['data[max]'])

        cur_page = page
        page -= 1
        per_page = max  # Set the number of results to display
        start = page * per_page

        # If search keyword is not empty, we include a query for searching
        # the "content" or "name" fields in the database for any matched strings.
        if search:
            all_posts = Product.objects.filter(Q(content__contains=search) | Q(name__contains=search),
                                               author=request.user.id).order_by(sort + name)[start:per_page]
            count = Product.objects.filter(Q(content__contains=search) | Q(name__contains=search),
                                           author=request.user.id).count()

        else:
            all_posts = Product.objects.filter(author=request.user.id).order_by(sort + name)[start:cur_page * max]
            count = Product.objects.filter(author=request.user.id).count()

        if all_posts:
            for post in all_posts:

ecommerce/templates/ecommerce/product/create.html
{% extends "ecommerce/base.html" %}
{% load i18n %}
{% block content %}
	<div class="container">
		<p>
			<a href = "/ecommerce/user/products" class="font-weight-bold"><span class="glyphicon glyphicon-chevron-left"></span> 
				<i class="fas fa-arrow-left"></i> &nbsp; <u>{% trans "All products" %}</u>
			</a>
		</p>
		
		<form method="post" action="{% url 'ecommerce:user_product_create' %}" class="row create-product">
			{% csrf_token %}
			<div class="col-md-8">
				<div class="form-group">
					<label for="{{ form.name.id_for_label }}">{% trans "Name" %}*</label>
					{{ form.name }}
				</div>
				<div class="form-group">
					<label for="{{ form.content.id_for_label }}">{% trans "Description" %}</label>
					{{ form.content }}
				</div>
				<div class="form-group">
					<label for="{{ form.excerpt.id_for_label }}">{% trans "Short Description" %}</label>
					{{ form.excerpt }}
				</div>
			</div>
			<div class="col-md-4">
				<div class="form-group">
					<label for="{{ form.price.id_for_label }}">{% trans "Price" %}"*</label>
					<div class="input-group">
						<div class="input-group-prepend">
							<span class="input-group-text" id="basic-addon1"><i class="fas fa-dollar-sign"></i></span>
						</div>
						{{ form.price }}
					</div>
				</div>
				<div class="form-group">
					<label for="{{ form.status.id_for_label }}">{% trans "Status" %}</label>
					{{ form.status }}
				</div>
				<div class="form-group">
					<label for="{{ form.quantity.id_for_label }}">{% trans "Quantity" %}*</label>
					{{ form.quantity }}
				</div>
				<input type="submit" class="btn btn-primary" value="{% trans 'Submit' %}" />
			</div>
		</form>
	</div>
{% endblock %}

ecommerce/templates/ecommerce/product/index.html
{% extends "ecommerce/base.html" %}
{% load i18n %}
{% block content %}
	<div class="container-fluid">
		{% csrf_token %}
		<form class = "post-list">
			<input type = "hidden" value = "" />
		</form>
		
		<div class="row">
			<div class="col-md-3">
				<div class="card">
					<div class="card-header">{% trans "Filter" %}</div>
					<div class="card-body">
						<div class="form-group">
							<label>البحث: </label>
							<input type="text" class="form-control post_search_text" placeholder="{% trans 'Enter a keyword' %}" />
						</div>
						<div class="form-group">
							<label>{% trans "Per Page" %}: </label>
							<select class="form-control post_max">
								<option value="4">4</option>
								<option value="8" selected>8</option>
								<option value="16">16</option>
							</select>
						</div>
						<div class="form-group">
							<label>{% trans "Order By" %}: </label>
							<select class="form-control post_name">
								<option value="name">اسم المنتج</option>
								<option value="price">السعر</option>
								<option value="quantity">السلع المتوفرة</option>
							</select>
						</div>
						<div class="form-group">
							<label>{% trans "Sorting" %}: </label>
							<select class="form-control post_sort">
								<option value="ASC">{% trans "Ascending" %}</option>
								<option value="DESC">{% trans "Descending" %}</option>
							</select>
						</div>
						<input type = "submit" value = "{% trans 'Filter' %}" class = "btn btn-primary btn-block post_search_submit" />
						
					</div>
				</div>
			</div>
			
			<div class="col-md-9">
				{% if request.GET.cart %}
					<div class="alert alert-success">
						{% if request.GET.cart == '0' %}
						{% trans "Item successfully removed from cart" %}
						{% else %}
							{% trans "Item successfully added to cart" %}
						{% endif %}
					</div>
				{% endif %}
				<div class="products-view-all">
					<div class="pagination-container row"></div>
					<div class="pagination-nav"></div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

ecommerce/templates/ecommerce/product/search.html
{% extends "ecommerce/base.html" %}
{% load i18n %}
{% block content %}
	<div class="container-fluid">
		{% csrf_token %}
		<form class = "post-list">
			<input type = "hidden" value = "" />

		<div class="row">
			<div class="col-md-3">
				<div class="card">
					<div class="card-header">{% trans "Filter" %}</div>
					<div class="card-body">
						<div class="form-group">
							<label>البحث: </label>
							<input type="text" name="keywords" class="form-control post_search_text"  placeholder="{% trans 'Enter a keyword' %}" value={{values.keywords}} >
							<input type="text" name="price" class="form-control post_search_text" placeholder="{% trans 'Enter a  price' %}" value={{values.price}}>
						</div>
                        <input type = "submit" value = "{% trans 'Filter' %}" class = "btn btn-primary btn-block post_search_submit" />
                    </div>
                </div>
            </div>
        </div>
        </form>

        <div class="py-5">
		<div class="container">
			<h2 class="text-center">افضل المنجات</h2>
			<hr>
			<div class="row">
				{% for item in products %}
					<div class='col-md-3 col-sm-6 mb-3'>
						<div class='card'>
							<div class='card-body p-0'>
								<a href="{% url 'ecommerce:single_product' item.id %}">
									<img src='/ar/ecommerce/{{ item.featured_image }}' width='253' height="300" class='img-responsive'>
								</a>
								<div class='list-group list-group-flush'>
									<div class='list-group-item border-top-0 py-2'>
										<i class='fa fa-shopping-cart fa-2x pr-3 pt-3 float-left'></i>
										<p class='list-group-item-text mb-0'>{% trans "Price" %}</p>
										<h4 class='list-group-item-heading'>{{ currency }} {{ item.price }}</h4>
									</div>
									<div class='list-group-item py-2'>
										<i class='fa fa-cubes fa-2x pr-3 pt-3 float-left'></i>
										<p class='list-group-item-text mb-0'>{% trans "On Stock" %}</p>
										<h4 class='list-group-item-heading'>{{ item.quantity }}</h4>
									</div>
								</div>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>

		</div>
	</div>
{% endblock %}

ecommerce/templates/ecommerce/product/single.html
{% extends "ecommerce/base.html" %}
{% load humanize %}
{% load i18n %}
{% block content %}		
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				{% if request.GET.cart %}
					<div class="alert alert-success alert-dismissable">
						{% if request.GET.cart == '0' %}
							{% trans "Item successfully removed from cart" %}
						{% else %}
							{% trans "Item successfully added to cart" %}
						{% endif %}
					</div>
				{% endif %}
			</div>
			
			<div class="col-md-8">
				<h3 class="mb-3">{{ product.name }}</h3>
				
				<input type = "hidden" class = "item-images-json" value = '{{ images }}' />
				<div class = "imageviewer">
					<div class = "image-container"></div>
					<i class="fas fa-arrow-circle-left prev"></i>
					<i class="fas fa-arrow-circle-right next"></i>
					
					<div class = "footer-info">
						<span class = "current"></span>/<span class="total"></span>
					</div>
				</div>
				
				<div class="card">
					<div class="card-header">{% trans "Details" %}</div>
					<div class="card-body">
						{{ product.content|safe }}
					</div>
				</div>
			</div>
			
			<div class="col-md-4">
				<div class="card">
					<div class="card-header">
						{% trans "Details" %}
					</div>
					<div class="card-body">
						<h2 class="text-danger">{{ currency }} {{ product.price|intcomma }}</h2>
						
						<p>{{ product.excerpt|linebreaks }}</p>
						
						<hr />
						
						<p><strong>{% trans "Date Posted" %}</strong>: {{ product.date }}</p>
						<p><strong>{% trans "On Stock" %}</strong>: {{ product.quantity }}</p>
						
						<hr />
						<form method="post" action="{% url 'ecommerce:cart' %}">
							{% if in_cart %}
								<input type="submit" value="{% trans 'Remove from Cart' %}" class="btn btn-block btn-danger" />
							{% else %}
								<div class="input-group">
									<div class="input-group-prepend">
										<div class="input-group-text">Qty</div>
									</div>
									<input type="number" id="quantity" min="1" max="{{ product.quantity }}" class="form-control" name="quantity" value="1" />
									<div class="input-group-append">
										<button type="submit" class="btn btn-primary">{% trans 'Add To Cart' %}</button>
									</div>
								</div>
							{% endif %}
							<input type="hidden" name="redirect" value="{% url 'ecommerce:single_product' product.id %}?cart={{ in_cart|yesno:'0,1' }}" />
							<input type="hidden" name="action" value="{{ in_cart|yesno:'delete,add' }}" />
							<input type="hidden" name="item_id" value="{{ product.id }}" />
					</div>
				</div>
				
				<div class="card">
					<div class="card-header">
						{% trans "Seller" %}
					</div>
					<div class="card-body">
						<p>
							<h3>{{ author.first_name }} {{ author.last_name }} </h3>
							<strong>{% trans "Email" %}:</strong> <a href="mailto:{{ author.email }}">{{ author.email }}</a><br />
							<strong>{% trans "Phone" %}  :</strong> <a href="tel:{{ author.member.phone_number }}">{{ author.member.phone_number }}</a>
						</p>
						
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

ecommerce/templates/ecommerce/product/update.html
{% extends "ecommerce/base.html" %}
{% load i18n %}
{% block content %}
	<div class="container item-edit" id="item-{{ product.id }}">
		<p>
			<u><a href = "{% url 'ecommerce:user_products' %}" class="font-weight-bold">{% trans "My Products" %}</a></u>&nbsp; |&nbsp;
			<u><a href = "{% url 'ecommerce:single_product' product.id %}" target="_blank" class="font-weight-bold">{% trans "View Product" %}</a></u>
		</p>
		
		<div class="wave-box-wrapper">
			<div class="wave-box"></div>
			<form action="{% url 'ecommerce:user_product_update' product.id %}" method="post" enctype="multipart/form-data" class="row update-product" >
				{% csrf_token %}
				<div class="col-md-8">
					<div class="form-group">
						<label for="{{ form.name.id_for_label }}">{% trans "Name" %}</label>
						{{ form.name }}
					</div>
					<div class="form-group">
						<label for="{{ form.content.id_for_label }}">{% trans "Description" %}</label>
						{{ form.content }}
					</div>
					<div class="form-group">
						<label for="{{ form.excerpt.id_for_label }}">{% trans "Short Description" %}</label>
						{{ form.excerpt }}
					</div>
					<div class="form-group">
						<label for="{{ form.images.id_for_label }}">{% trans "Upload Images" %}</label>
						{{ form.images }}
						<hr />
						
						<div class="images-section row">
							{% if product.image_set.all %}
								{% for data in product.image_set.all %}
									<div class="col-sm-3 mb-3">
										<i class="unset-image fas fa-trash-alt text-danger mr-2 c-p" id="unset-{{ data.id }}" title="Delete image"></i>
										{% if product.featured_image == data.image %}
											<i class="set-featured-image fas fa-star c-p" title="Set as featured image" id="featured-{{ data.image }}" style="color: #E4C317"></i>
										{% else %}
											<i class="set-featured-image far fa-star c-p" title="Set as featured image" id="featured-{{ data.image }}"></i>
										{% endif %}
										<div>
											<img src = "/ar/ecommerce/{{ data.image }}" class="img-thumbnail img-responsive" />
										</div>
									</div>
									
									{% if forloop.counter|divisibleby:4 == 1 %}
										<div class="clearfix"></div>
									{% endif %}
								{% endfor %}
							{% else %}
								<div class="alert alert-danger no-item-images w-100 mx-3">{% trans "No images found" %}</div>
							{% endif %}
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
						<label for="{{ form.price.id_for_label }}">{% trans "Price" %}</label>
						<div class="input-group">
							<div class="input-group-prepend">
								<span class="input-group-text" id="basic-addon1"><i class="fas fa-dollar-sign"></i></span>
							</div>
							{{ form.price }}
						</div>
					</div>
					<div class="form-group">
						<label for="{{ form.status.id_for_label }}">{% trans "Status" %}</label>
						{{ form.status }}
					</div>
					<div class="form-group">
						<label for="{{ form.quantity.id_for_label }}">{% trans "Quantity" %}</label>
						{{ form.quantity }}
					</div>
					<input type="submit" class="btn btn-primary" value="{% trans  'Update' %}" />
				</div>
			</form>
		</div>
	</div>
{% endblock %}

ecommerce/templates/ecommerce/product/user.html
{% extends "ecommerce/base.html" %}

{% block content %}
	<div class="container products-view-user">
		{% csrf_token %}
		<form class = "post-list">
			<input type = "hidden" value = "" />
		</form>
		
		<div class="form-inline float-left">
			<label> الصفحة:</label>
			<select class="form-control ml-sm-2 post_max">
				<option value="5">5</option>
				<option value="10" selected>10</option>
				<option value="15">15</option>
			</select>
		
			<label class="ml-sm-3 mt-3 mt-xl-0">البحث:</label>
			<input type="text" class="form-control ml-sm-2 post_search_text" placeholder="Enter a keyword">
			<input type = "submit" value = "Filter" class = "btn btn-primary mt-3 mt-xl-0 post_search_submit" />
		</div>
		
		<a href="/ecommerce/user/product/create/" class="btn btn-primary mb-3 float-right">اضافة</a>
		
		<br class = "clear" />
		
		<div class = "wave-box-wrapper">
			<div class = "wave-box"></div>
			<div class = "table-responsive">
				<table class = "table table-striped table-post-list">
					<thead>
						<tr>
							<th>الصورة</th>
							<th id = "name" class = "active"><a href = "#">الاسم</a></th>
							<th id = "price"><a href = "#">السعر</a></th>
							<th id = "status"><a href = "#">الحالة</a></th>
							<th id = "date"><a href = "#">التاريخ</a></th>
							<th id = "quantity"><a href = "#">الكمية</a></th>
							<th>الحساب</th>
						</tr>
					</thead>
					<tbody class = "pagination-container"></tbody>
				</table>
			</div>
			<div class = "pagination-nav"></div>
		</div>
	</div>
{% endblock %}