ecommerce/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'ecommerce'  # This will be like this: {% url 'ecommerce:detail' item.id %} on our templates.
urlpatterns = [
                  url(r'^$', views.index, name='index'),
                  url(r'^products/$', views.products, name='products'),
                  url(r'^product/(?P<product_id>[0-9]+)/$', views.single_product, name='single_product'),
                  url(r'^about/$', views.about, name='about'),
                  url(r'^contact/$', views.contact, name='contact'),
                  url(r'^cart/$', views.cart, name='cart'),
                  url(r'^checkout/$', views.checkout, name='checkout'),
                  url(r'^payment-paypal$', views.payment_paypal, name='payment-paypal'),
                  url(r'^cash-on-delivery$', views.checkout_cash_on_delivery, name='checkout-cash-on-delivery'),
                  url(r'^cash-on-delivery/order/created/$', views.cash_on_delivery_order_created,
                      name='cash_on_delivery_created'),
                  url(r'^checkout/paypal$', views.checkout_paypal, name='paypal-checkout'),
                  url(r'^checkout/payment/process/$', views.proceed_to_pay, name='proceed-to-pay'),
                  url(r'^search/$', views.product_search, name='search'),

                  url(r'^user/', include([
                      url(r'^login/$', views.user_login, name='user_login'),
                      url(r'^register/$', views.user_register, name='user_register'),
                      url(r'^account/$', views.user_account, name='user_account'),
                      url(r'^products/$', views.user_products, name='user_products'),
                      url(r'^product/create/$', views.user_product_create, name='user_product_create'),
                      url(r'^product/update/(?P<product_id>[0-9]+)/$', views.user_product_update,
                          name='user_product_update'),
                      url(r'^product/update/set-featured-image/', views.set_featured_image),
                      url(r'^product/update/unset-image/$', views.unset_image),
                      url(r'^product/unset-product/$', views.unset_product),
                      url(r'^logout/$', views.logout),
                  ])),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insight/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = i18n_patterns(
        url(r'^ecommerce/', include('ecommerce.urls')),  # Include ecommerce app views.
        url(r'^admin/', admin.site.urls),

)

ecommerce/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Product

class RegisterForm(forms.Form):
    username = forms.CharField(label=_("username"), widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label=_("email"), widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label=_("password"), widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password_repeat = forms.CharField(label=_("password_repeat"),
                                      widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(label=_("first_name"), widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label=_("last_name"), widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(label=_("phone_number"), widget=forms.NumberInput(attrs={'class': 'form-control'}),
                                   required=False)


class AccountForm(forms.Form):
    username = forms.CharField(label=_("username"), widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label=_("email"), widget=forms.EmailInput(attrs={'class': 'form-control'}))
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Leave blank if no change'}),
        required=False, label=_("old_password"))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Leave blank if no change'}),
        required=False, label=_("password"))
    password_repeat = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Leave blank if no change'}),
        required=False, label=_("password_repeat"))
    first_name = forms.CharField(label=_("first_name"), widget=forms.TextInput(attrs={'class': 'form-control'}, ))
    last_name = forms.CharField(label=_("last_name"), widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(label=_("phone_number"), widget=forms.NumberInput(attrs={'class': 'form-control'}),
                                   required=False)
    about_me = forms.CharField(label=_("about_me"),
                               widget=forms.Textarea(attrs={'class': 'form-control', 'id': 'ck-editor-area'}),
                               required=False)


class CreateProductForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'id': 'ck-editor-area'}))
    excerpt = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '7'}), required=False)
    price = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Amount'}))
    status = forms.CharField(
        widget=forms.Select(choices=(('1', 'Active'), ('0', 'Inactive'),), attrs={'class': 'form-control'}))
    quantity = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-control'}))


class UpdateProductForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'id': 'ck-editor-area'}))
    excerpt = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '7'}), required=False)
    images = forms.CharField(widget=forms.FileInput(
        attrs={'class': 'form-control image-input', 'accept': 'image/*', 'multiple': 'multiple'}), required=False)
    price = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Amount'}))
    status = forms.CharField(
        widget=forms.Select(choices=(('1', 'Active'), ('0', 'Inactive'),), attrs={'class': 'form-control'}))
    quantity = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-control'}))


class Product_Create(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('featured_image',)

ecommerce/views.py
import os
import re
from time import gmtime, strftime

import braintree
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, \
    login  # Use alias like "django_logout" so that django doesnt get confused on which function to use.
from django.contrib.humanize.templatetags.humanize import intcomma
from django.core.files.storage import FileSystemStorage
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.template.defaulttags import register
from django.views.decorators.csrf import csrf_exempt

from orders.forms import OrderCreateForm
from orders.models import Order, OrderItem
from .apps import EcommerceConfig
from .forms import *
from .helpers import Helpers
from .models import Member, Product, Image, User

paypal_access_token = "access_token$sandbox$8f9htcykq255v55n$d8e95f2daddb1d62da6199d05352bb4a"


def index(request):
    preview_products = Product.objects.all().order_by('-id')[:12]

    return render(request, Helpers.get_url('index.html'),
                  {'products': preview_products, 'currency': EcommerceConfig.currency})


def single_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    author = get_object_or_404(User, pk=product.author)
    product_images = product.image_set.all()
    images = []
    cart_items = request.session

    # Create an empty cart object if it does not exist yet
    if not cart_items.has_key("cart"):
        cart_items["cart"] = {}

    in_cart = True if cart_items['cart'].get(str(product_id)) else False

    if product_images:
        for data in product_images:
            images.append({"small": Helpers.get_path(str(data.image)), 'big': Helpers.get_path(str(data.image))})

    return render(request, Helpers.get_url('product/single.html'),
                  {'product': product, 'images': str(images).replace("'", '"'), 'in_cart': in_cart, 'author': author,
                   'currency': EcommerceConfig.currency})


def products(request):
    if request.method == 'POST':
        pagination_content = ""
        page_number = request.POST['data[page]'] if request.POST['data[page]'] else 1
        page = int(page_number)
        name = request.POST['data[name]']
        sort = '-' if request.POST['data[sort]'] == 'DESC' else ''
        search = request.POST['data[search]']
        max = int(request.POST['data[max]'])

        cur_page = page
        page -= 1
        per_page = max  # Set the number of results to display
        start = page * per_page

        # If search keyword is not empty, we include a query for searching
        # the "content" or "name" fields in the database for any matched strings.
        if search:
            all_posts = Product.objects.filter(Q(content__contains=search) | Q(name__contains=search)).exclude(
                status=0).order_by(sort + name)[start:per_page]
            count = Product.objects.filter(Q(content__contains=search) | Q(name__contains=search)).exclude(
                status=0).count()

        else:
            all_posts = Product.objects.exclude(status=0).order_by(sort + name)[start:cur_page * max]
            count = Product.objects.exclude(status=0).count()

    else:
        return render(request, 'ecommerce/product/index.html')


def product_search(request):
    queryset_list = Product.objects.order_by('-date')
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(excerpt__icontains=keywords)
    if 'price' in request.GET:
        price = request.GET['price']
        queryset_list = queryset_list.filter(price__icontains=price)

    context = {
        'products': queryset_list,
        'values': request.GET
    }
    return render(request, Helpers.get_url('product/search.html'), context)


def about(request):
    return render(request, Helpers.get_url('about.html'))


def contact(request):
    return render(request, Helpers.get_url('contact.html'))


def paymentDetails(request):
    return render(request, Helpers.get_url('payment-details.html'))


def user_login(request):
    # Redirect if already logged-in
    if request.user.is_authenticated:
        return HttpResponseRedirect(Helpers.get_path('user/account'))

    if request.method == 'POST':
        # Process the request if posted data are available
        username = request.POST['username']
        password = request.POST['password']
        # Check username and password combination if correct
        user = authenticate(username=username, password=password)
        if user is not None:
            # Success, now let's login the user.
            login(request, user)
            # Then redirect to the accounts page.
            return HttpResponseRedirect(Helpers.get_path('user/account'))
        else:
            # Incorrect credentials, let's throw an error to the screen.
            return render(request, Helpers.get_url('user/login.html'),
                          {'error_message': 'Incorrect username and / or password.'})
    else:
        # No post data availabe, let's just show the page to the user.
        return render(request, Helpers.get_url('user/login.html'))


def user_account(request):
    err_succ = {'status': 0, 'message': 'An unknown error occured'}

    # Create instance of the form and populate it with requests
    form = AccountForm(request.POST)

    # Redirect if not logged-in
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(Helpers.get_path('user/login'))

    if request.method == 'POST':
        if form.is_valid():
            # Query data of currently logged-in user.
            user = User.objects.get(username=request.user.username)

            # Check if username exists
            if User.objects.filter(username=form.cleaned_data['username']).exists() and user.username != \
                    form.cleaned_data['username']:
                err_succ['message'] = 'Username aleady taken, please enter a different one.'

            # Check if email exists
            elif User.objects.filter(email=form.cleaned_data['email']).exists() and user.email != form.cleaned_data[
                'email']:
                err_succ['message'] = 'Email already taken, please enter a different one'

            elif form.cleaned_data['old_password'] and form.cleaned_data['password_repeat'] and form.cleaned_data[
                'password']:
                # Check if passwords match
                if form.cleaned_data['password_repeat'] != form.cleaned_data['password']:
                    err_succ['message'] = 'New password do not match.'

                # Check if old password is correct
                elif not user.check_password(form.cleaned_data['old_password']):
                    err_succ['message'] = 'Incorrect old password.'

            else:
                user.username = form.cleaned_data['username']
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']

                user.member.phone_number = form.cleaned_data['phone_number']
                user.member.about = form.cleaned_data['about_me']

                # Save new password if passes above validations
                if form.cleaned_data['password']:
                    user.set_password(form.cleaned_data['password'])

                # Save posted fields to their respective tables
                user.member.save()
                user.save()

                # Show success message
                err_succ['status'] = 1
                err_succ['message'] = 'Account successfully updated.'

        return JsonResponse(err_succ)
    else:
        # Let's define intial data that we are going to use to popul
        # ate our account form.
        user_data = {
            'username': request.user.username,
            'email': request.user.email,
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'phone_number': request.user.member.phone_number,
            'about_me': request.user.member.about
        }
        # Render the account form
        return render(request, Helpers.get_url('user/account.html'), {'form': AccountForm(initial=user_data)})


def user_products(request):
    # Redirect if not logged-in
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(Helpers.get_path('user/login'))

    if request.method == 'POST':
        pagination_content = ""
        page_number = request.POST['data[page]'] if request.POST['data[page]'] else 1
        page = int(page_number)
        name = request.POST['data[th_name]']
        sort = '-' if request.POST['data[th_sort]'] == 'DESC' else ''
        search = request.POST['data[search]']
        max = int(request.POST['data[max]'])

        cur_page = page
        page -= 1
        per_page = max  # Set the number of results to display
        start = page * per_page

        # If search keyword is not empty, we include a query for searching
        # the "content" or "name" fields in the database for any matched strings.
        if search:
            all_posts = Product.objects.filter(Q(content__contains=search) | Q(name__contains=search),
                                               author=request.user.id).order_by(sort + name)[start:per_page]
            count = Product.objects.filter(Q(content__contains=search) | Q(name__contains=search),
                                           author=request.user.id).count()

        else:
            all_posts = Product.objects.filter(author=request.user.id).order_by(sort + name)[start:cur_page * max]
            count = Product.objects.filter(author=request.user.id).count()

        if all_posts:
            for post in all_posts:

ecommerce/templates/ecommerce/cart.html
{% extends "ecommerce/base.html" %}
{% load humanize %}

{% block content %}
	<div class="container">
		<h2>السلة</h2>
		<br />
		
		{% if request.GET.cart %}
			<div class="alert alert-success alert-dismissable">
				{% if request.GET.cart == '0' %}
				تم الحذف من السلة
				{% else %}
				تم تحديث المنتج
				{% endif %}
			</div>
		{% endif %}
		
		{% if cart_db_items %}
			<div class="table-responsive">
				<table class="table table-bordered">
					<tr>
						<th>المنتج</th>
						<th>الكمية</th>
						<th>المجموع</th>
						<th>تاريخ الاضافة</th>
						<th>#</th>
					</tr>
					
					{% for item in cart_db_items %}
						{% with cart_session_items|get_cart_item:item.id as cart %}  
						<tr>
							<td>
								<a href="{% url 'ecommerce:single_product' item.id %}">
									<img src="/ar/ecommerce/{{ item.featured_image }}" class="img-responsive img-thumbnail float-left mr-2" width="50">
									{{ item.name }}
								</a>
							</td>
							<td>
								<form method="post" action="{% url 'ecommerce:cart' %}" class="form-inline">
									<input type="hidden" name="redirect" value="{% url 'ecommerce:cart' %}?cart=1" />
									<input type="hidden" name="action" value="edit" />
									<input type="hidden" name="item_id" value="{{ item.id }}" />
									<input type="number" name="quantity" style="width: 70px;" class="form-control" min="1" max="{{ item.quantity }}" value="{{ cart.quantity }}" />
									<button type="submit" class="btn btn-link"><span class="glyphicon glyphicon-floppy-save"></span> تحديث</button>
								</form>
							</td>
							<td>{{ currency }} {% multiply cart.quantity item.price %}</td>
							<td>{{ cart.date_added }}</td>
							<td>
								<form method="post" action="{% url 'ecommerce:cart' %}">
									<input type="hidden" name="redirect" value="{% url 'ecommerce:cart' %}?cart=0" />
									<input type="hidden" name="action" value="delete" />
									<input type="hidden" name="item_id" value="{{ item.id }}" />
									<button type="submit" class="btn btn-link"><span class="glyphicon glyphicon-trash"></span> حذف</button>
								</form>
							</td>
						</tr>
						{% endwith %}
					{% endfor %}
				</table>
			</div>
			
			<div class="row">
				<div class="col-sm-6"></div>
				<div class="col-sm-6">
					<h3>مجموع السلة</h3>
					<table class="table table-bordered">
						<tr>
							<th>المجموع الفرعي</th>
							<td>{{ currency }} {{ cart_total }}</td>
						</tr>
						<tr>
							<th>المجموع</th>
							<td>{{ currency }} {{ cart_total }}</td>
						</tr>
					</table>

					<a href="{% url 'ecommerce:checkout-cash-on-delivery' %}" class="btn btn-block btn-lg btn-primary">الدفع عند الاستلام</a>
					<a href="{% url 'ecommerce:paypal-checkout' %}" class="btn btn-block btn-lg btn-primary">  Paypalالدفع عن طريق </a>

				</div>
			</div>
		{% else %}
			<div class="alert alert-danger alert-dismissable">السلة فارغة</div>
		{% endif %}
	</div>
{% endblock %}

ecommerce/templates/ecommerce/checkout.html
{% extends "ecommerce/base.html" %}
{% load humanize %}
{% load widget_tweaks %}
{% load countries %}
{% block content %}
<style>
    #paypal_method {
        cursor: pointer;
    }

    #paypal_method:hover {
        background-color: #F2F2F2;
    }

    .zoid-outlet {
        width: 110px !important;
        height: 48px !important;
        opacity: 0;
    }

    .success-form {
        background-color: #D4EDDA;
        padding: 4px 10px 4px 10px;
        border-radius: 4px;
        width: 100%;
        color: #4CAF50;
        font-size: 30px;
        margin-right: 20px;
        display: none;
    }
</style>

<div class="container">
    <h2>تاكيد</h2>
    <br/>

    {% if cart_db_items %}
        <div class="col-lg-12">
            <h4 class="upper">Billing & Shipping Address</h4>
        </div>
        <form method="post" novalidate>
            {% csrf_token %}
            <div class="col-lg-8 ">

                {% for hidden_field in form.hidden_fields %}
                {{ hidden_field }}
                {% endfor %}

                {% if form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    {% for error in form.non_field_errors %}
                    {{ error }}
                    {% endfor %}
                </div>
                {% endif %}

                {% for field in form.visible_fields %}
                <div class="form-group">
                    {{ field.label_tag }}

                    {% if form.is_bound %}
                    {% if field.errors %}
                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                    {% else %}
                    {% render_field field class="form-control is-valid" %}
                    {% endif %}
                    {% else %}
                    {% render_field field class="form-control" %}
                    {% endif %}

                    {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                </div>
                {% endfor %}
            </div>


        <div class="seperator"><i class="fa fa-credit-card"></i></div>


        <div class="col-sm-12 my-4">
            <div class="card">
                <div class="card-header">
                    <h4>طلبك</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <tr>
                                <th>المنتج</th>
                                <th>المجموع</th>
                            </tr>
                            {% for item in cart_db_items %}
                            {% with cart_session_items|get_cart_item:item.id as cart %}
                            <tr>
                                <td>
                                    <a href="{% url 'ecommerce:single_product' item.id %}">
                                        <img src="/ecommerce/{{ item.featured_image }}"
                                             class="img-responsive img-thumbnail mr-2 float-left" width="50">
                                        {{ item.name }}</a>&nbsp; x {{ cart.quantity }}
                                    </a>
                                </td>
                                <td>{{ currency }} {% multiply cart.quantity item.price %}</td>
                            </tr>
                            {% endwith %}
                            {% endfor %}

                            <tr>
                                <th>المجموع الفرعي</th>
                                <td><strong>{{ currency }} {{ cart_total|intcomma }}</strong></td>
                            </tr>
                            <tr>
                                <th>المجموع</th>
                                <td><strong>{{ currency }} {{ cart_total|intcomma }}</strong></td>
                            </tr>
                        </table>
                    </div>

                    <br/>
                    <input type="checkbox" name="terms_and_conditions"/>&nbsp; I’ve read and accept the <a href="#">terms
                    & conditions</a>
                    <div class="row" style="padding:20px;">
                        <div class="col-sm-10">
                            <p class="float-right success-form" id="paid-msg" align="center"><font><b>تم الدفع بنجاح</font></b></p>
                        </div>
                        <div class="col-sm-2" style="padding: 0px;">
                            <input type="button" class="btn btn-primary btn-lg float-right"
                                   value="pay now"/>
                            <div id="paypal-button" class="float-right"
                                 style="margin-right: -110px; margin-top: 11px;"></div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning mt-3" href="#"><span>حفظ التغيرات
                </span></button>
                </div>
                <br/>


            </div>


            <script src="https://www.paypalobjects.com/api/checkout.js" data-version-4></script>
            <!-- Load the client component. -->
            <script src="https://js.braintreegateway.com/web/3.62.1/js/client.min.js"></script>
            <!-- Load the PayPal Checkout component. -->
            <script src="https://js.braintreegateway.com/web/3.62.1/js/paypal-checkout.min.js"></script>
            <script>
                paypal.Button.render({
                    braintree: braintree,
                    client: {
                        production: "{{ paypal_key }}",
                        sandbox: "{{ paypal_key }}",
                    },
                    env: 'sandbox', // Or 'product'
                    commit: true, // This will add the transaction amount to the PayPal button

                    payment: function (data, actions) {
                        return actions.braintree.create({
                            flow: 'checkout', // Required
                            amount: "{{ cart_total|intcomma }}", // Required
                            currency: 'USD', // Required

                        });
                    },

                    onAuthorize: function (payload) {
                        // Submit `payload.nonce` to your server.
                        $(".spinner-box").show();
                        $.ajax({
                            headers: {"X-CSRFToken": '{{csrf_token}}'},
                            url: '{% url "ecommerce:payment-paypal" %}',
                            type: 'POST',
                            data: {
                                payment_method_nonce: payload.nonce,
                                amount: "{{ cart_total|intcomma }}",
                                description: "PayPal result file",
                            },
                            success: function (data) {
                                $(".spinner-box").hide();
                                if (data['statusCode'] == 1) {
                                    $("#paid-msg").css("display", "block");
                                } else {
                                    alert("Processing was failed.");
                                }
                            },
                            error: function (data) {
                                false;
                            }
                        });
                    },
                }, '#paypal-button');
            </script>
            {% else %}
            <div class="alert alert-danger alert-dismissable">السلة فارغة</div>
            {% endif %}
        </div>
        {% endblock %}

ecommerce/templates/ecommerce/contact.html
{% extends "ecommerce/base.html" %}
{% load i18n %}
{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-md-8 offset-md-2">
				<h2>تواصل معنا</h2>
				<br />
				<table class="table">
					<tr>	
						<th><i class="fa fa-home fa-1x"></i> الموقع:</th>               
						<td>الرياض,الآندلس</td>
					</tr>
					<tr>
						<th><i class="fa fa-envelope fa-1x"></i>{% trans "E-Mail Address" %} :</th>
						<td><a href="mailto:carl.fontanos@gmail.com">nona@gmail.com</a></td>
					</tr>
					
					<tr>
						<th><i class="fa fa-link fa-1x"></i>{% trans "Website" %}:</th>
						<td><a href="http://www.carlofontanos.com">www.infinitymarket.com</a></td>
					</tr>
				</table>
				<br >
				
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3827.4021417487606!2d120.59976289999999!3d16.4043903!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3391a141aa154c0f%3A0x36133249722cd8fa!2sBaguio+Convention+Center!5e0!3m2!1sen!2sph!4v1530511139735" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
			</div>
		</div>
	</div>
       

{% endblock %}

ecommerce/templates/ecommerce/index.html
{% extends "ecommerce/base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
	
	<div id="home-carousel" class="carousel slide" data-ride="carousel" style="margin-top: -15px;">
		<ol class="carousel-indicators">
			<li data-target="#home-carousel" data-slide-to="0" class="active"></li>
			<li data-target="#home-carousel" data-slide-to="1"></li>
		</ol>
		<div class="carousel-inner">
			<div class="carousel-item active">
				<img src="{% static 'ecommerce/img/womens_banner.jpg' %}" class="d-block w-100" alt="...">
			</div>
			<div class="carousel-item">
				<img src="{% static 'ecommerce/img/mens_banner.jpg' %}" class="d-block w-100" alt="...">
			</div>
		</div>
		<a class="carousel-control-prev" href="#home-carousel" role="button" data-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="carousel-control-next" href="#home-carousel" role="button" data-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>
	
	
	<div class="py-5">
		<div class="container">
			<h2 class="text-center">افضل المنجات</h2>
			<hr>
			<div class="row">
				{% for item in products %}
					<div class='col-md-3 col-sm-6 mb-3'>
						<div class='card'>
							<div class='card-body p-0'>
								<a href="{% url 'ecommerce:single_product' item.id %}">
									<img src='{{ item.featured_image }}' width='253' height="300" class='img-responsive'>
								</a>
								<div class='list-group list-group-flush'>
									<div class='list-group-item border-top-0 py-2'>
										<i class='fa fa-shopping-cart fa-2x pr-3 pt-3 float-left'></i>
										<p class='list-group-item-text mb-0'>{% trans "Price" %}</p>
										<h4 class='list-group-item-heading'>{{ currency }} {{ item.price }}</h4>
									</div>
									<div class='list-group-item py-2'>
										<i class='fa fa-cubes fa-2x pr-3 pt-3 float-left'></i>
										<p class='list-group-item-text mb-0'>{% trans "On Stock" %}</p>
										<h4 class='list-group-item-heading'>{{ item.quantity }}</h4>
									</div>
								</div>
							</div> 
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
	
{% endblock %}