ecommerce/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'ecommerce'  # This will be like this: {% url 'ecommerce:detail' item.id %} on our templates.
urlpatterns = [
                  url(r'^$', views.index, name='index'),
                  url(r'^products/$', views.products, name='products'),
                  url(r'^product/(?P<product_id>[0-9]+)/$', views.single_product, name='single_product'),
                  url(r'^about/$', views.about, name='about'),
                  url(r'^contact/$', views.contact, name='contact'),
                  url(r'^cart/$', views.cart, name='cart'),
                  url(r'^checkout/$', views.checkout, name='checkout'),
                  url(r'^payment-paypal$', views.payment_paypal, name='payment-paypal'),
                  url(r'^cash-on-delivery$', views.checkout_cash_on_delivery, name='checkout-cash-on-delivery'),
                  url(r'^cash-on-delivery/order/created/$', views.cash_on_delivery_order_created,
                      name='cash_on_delivery_created'),
                  url(r'^checkout/paypal$', views.checkout_paypal, name='paypal-checkout'),
                  url(r'^checkout/payment/process/$', views.proceed_to_pay, name='proceed-to-pay'),
                  url(r'^search/$', views.product_search, name='search'),

                  url(r'^user/', include([
                      url(r'^login/$', views.user_login, name='user_login'),
                      url(r'^register/$', views.user_register, name='user_register'),
                      url(r'^account/$', views.user_account, name='user_account'),
                      url(r'^products/$', views.user_products, name='user_products'),
                      url(r'^product/create/$', views.user_product_create, name='user_product_create'),
                      url(r'^product/update/(?P<product_id>[0-9]+)/$', views.user_product_update,
                          name='user_product_update'),
                      url(r'^product/update/set-featured-image/', views.set_featured_image),
                      url(r'^product/update/unset-image/$', views.unset_image),
                      url(r'^product/unset-product/$', views.unset_product),
                      url(r'^logout/$', views.logout),
                  ])),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insight/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = i18n_patterns(
        url(r'^ecommerce/', include('ecommerce.urls')),  # Include ecommerce app views.
        url(r'^admin/', admin.site.urls),

)

ecommerce/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Product

class RegisterForm(forms.Form):
    username = forms.CharField(label=_("username"), widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label=_("email"), widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label=_("password"), widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password_repeat = forms.CharField(label=_("password_repeat"),
                                      widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(label=_("first_name"), widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label=_("last_name"), widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(label=_("phone_number"), widget=forms.NumberInput(attrs={'class': 'form-control'}),
                                   required=False)


class AccountForm(forms.Form):
    username = forms.CharField(label=_("username"), widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label=_("email"), widget=forms.EmailInput(attrs={'class': 'form-control'}))
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Leave blank if no change'}),
        required=False, label=_("old_password"))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Leave blank if no change'}),
        required=False, label=_("password"))
    password_repeat = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Leave blank if no change'}),
        required=False, label=_("password_repeat"))
    first_name = forms.CharField(label=_("first_name"), widget=forms.TextInput(attrs={'class': 'form-control'}, ))
    last_name = forms.CharField(label=_("last_name"), widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(label=_("phone_number"), widget=forms.NumberInput(attrs={'class': 'form-control'}),
                                   required=False)
    about_me = forms.CharField(label=_("about_me"),
                               widget=forms.Textarea(attrs={'class': 'form-control', 'id': 'ck-editor-area'}),
                               required=False)


class CreateProductForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'id': 'ck-editor-area'}))
    excerpt = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '7'}), required=False)
    price = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Amount'}))
    status = forms.CharField(
        widget=forms.Select(choices=(('1', 'Active'), ('0', 'Inactive'),), attrs={'class': 'form-control'}))
    quantity = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-control'}))


class UpdateProductForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'id': 'ck-editor-area'}))
    excerpt = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '7'}), required=False)
    images = forms.CharField(widget=forms.FileInput(
        attrs={'class': 'form-control image-input', 'accept': 'image/*', 'multiple': 'multiple'}), required=False)
    price = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Amount'}))
    status = forms.CharField(
        widget=forms.Select(choices=(('1', 'Active'), ('0', 'Inactive'),), attrs={'class': 'form-control'}))
    quantity = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-control'}))


class Product_Create(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('featured_image',)

ecommerce/views.py
import os
import re
from time import gmtime, strftime

import braintree
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, \
    login  # Use alias like "django_logout" so that django doesnt get confused on which function to use.
from django.contrib.humanize.templatetags.humanize import intcomma
from django.core.files.storage import FileSystemStorage
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.template.defaulttags import register
from django.views.decorators.csrf import csrf_exempt

from orders.forms import OrderCreateForm
from orders.models import Order, OrderItem
from .apps import EcommerceConfig
from .forms import *
from .helpers import Helpers
from .models import Member, Product, Image, User

paypal_access_token = "access_token$sandbox$8f9htcykq255v55n$d8e95f2daddb1d62da6199d05352bb4a"


def index(request):
    preview_products = Product.objects.all().order_by('-id')[:12]

    return render(request, Helpers.get_url('index.html'),
                  {'products': preview_products, 'currency': EcommerceConfig.currency})


def single_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    author = get_object_or_404(User, pk=product.author)
    product_images = product.image_set.all()
    images = []
    cart_items = request.session

    # Create an empty cart object if it does not exist yet
    if not cart_items.has_key("cart"):
        cart_items["cart"] = {}

    in_cart = True if cart_items['cart'].get(str(product_id)) else False

    if product_images:
        for data in product_images:
            images.append({"small": Helpers.get_path(str(data.image)), 'big': Helpers.get_path(str(data.image))})

    return render(request, Helpers.get_url('product/single.html'),
                  {'product': product, 'images': str(images).replace("'", '"'), 'in_cart': in_cart, 'author': author,
                   'currency': EcommerceConfig.currency})


def products(request):
    if request.method == 'POST':
        pagination_content = ""
        page_number = request.POST['data[page]'] if request.POST['data[page]'] else 1
        page = int(page_number)
        name = request.POST['data[name]']
        sort = '-' if request.POST['data[sort]'] == 'DESC' else ''
        search = request.POST['data[search]']
        max = int(request.POST['data[max]'])

        cur_page = page
        page -= 1
        per_page = max  # Set the number of results to display
        start = page * per_page

        # If search keyword is not empty, we include a query for searching
        # the "content" or "name" fields in the database for any matched strings.
        if search:
            all_posts = Product.objects.filter(Q(content__contains=search) | Q(name__contains=search)).exclude(
                status=0).order_by(sort + name)[start:per_page]
            count = Product.objects.filter(Q(content__contains=search) | Q(name__contains=search)).exclude(
                status=0).count()

        else:
            all_posts = Product.objects.exclude(status=0).order_by(sort + name)[start:cur_page * max]
            count = Product.objects.exclude(status=0).count()

    else:
        return render(request, 'ecommerce/product/index.html')


def product_search(request):
    queryset_list = Product.objects.order_by('-date')
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(excerpt__icontains=keywords)
    if 'price' in request.GET:
        price = request.GET['price']
        queryset_list = queryset_list.filter(price__icontains=price)

    context = {
        'products': queryset_list,
        'values': request.GET
    }
    return render(request, Helpers.get_url('product/search.html'), context)


def about(request):
    return render(request, Helpers.get_url('about.html'))


def contact(request):
    return render(request, Helpers.get_url('contact.html'))


def paymentDetails(request):
    return render(request, Helpers.get_url('payment-details.html'))


def user_login(request):
    # Redirect if already logged-in
    if request.user.is_authenticated:
        return HttpResponseRedirect(Helpers.get_path('user/account'))

    if request.method == 'POST':
        # Process the request if posted data are available
        username = request.POST['username']
        password = request.POST['password']
        # Check username and password combination if correct
        user = authenticate(username=username, password=password)
        if user is not None:
            # Success, now let's login the user.
            login(request, user)
            # Then redirect to the accounts page.
            return HttpResponseRedirect(Helpers.get_path('user/account'))
        else:
            # Incorrect credentials, let's throw an error to the screen.
            return render(request, Helpers.get_url('user/login.html'),
                          {'error_message': 'Incorrect username and / or password.'})
    else:
        # No post data availabe, let's just show the page to the user.
        return render(request, Helpers.get_url('user/login.html'))


def user_account(request):
    err_succ = {'status': 0, 'message': 'An unknown error occured'}

    # Create instance of the form and populate it with requests
    form = AccountForm(request.POST)

    # Redirect if not logged-in
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(Helpers.get_path('user/login'))

    if request.method == 'POST':
        if form.is_valid():
            # Query data of currently logged-in user.
            user = User.objects.get(username=request.user.username)

            # Check if username exists
            if User.objects.filter(username=form.cleaned_data['username']).exists() and user.username != \
                    form.cleaned_data['username']:
                err_succ['message'] = 'Username aleady taken, please enter a different one.'

            # Check if email exists
            elif User.objects.filter(email=form.cleaned_data['email']).exists() and user.email != form.cleaned_data[
                'email']:
                err_succ['message'] = 'Email already taken, please enter a different one'

            elif form.cleaned_data['old_password'] and form.cleaned_data['password_repeat'] and form.cleaned_data[
                'password']:
                # Check if passwords match
                if form.cleaned_data['password_repeat'] != form.cleaned_data['password']:
                    err_succ['message'] = 'New password do not match.'

                # Check if old password is correct
                elif not user.check_password(form.cleaned_data['old_password']):
                    err_succ['message'] = 'Incorrect old password.'

            else:
                user.username = form.cleaned_data['username']
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']

                user.member.phone_number = form.cleaned_data['phone_number']
                user.member.about = form.cleaned_data['about_me']

                # Save new password if passes above validations
                if form.cleaned_data['password']:
                    user.set_password(form.cleaned_data['password'])

                # Save posted fields to their respective tables
                user.member.save()
                user.save()

                # Show success message
                err_succ['status'] = 1
                err_succ['message'] = 'Account successfully updated.'

        return JsonResponse(err_succ)
    else:
        # Let's define intial data that we are going to use to popul
        # ate our account form.
        user_data = {
            'username': request.user.username,
            'email': request.user.email,
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'phone_number': request.user.member.phone_number,
            'about_me': request.user.member.about
        }
        # Render the account form
        return render(request, Helpers.get_url('user/account.html'), {'form': AccountForm(initial=user_data)})


def user_products(request):
    # Redirect if not logged-in
    if request.user.is_authenticated == False:
        return HttpResponseRedirect(Helpers.get_path('user/login'))

    if request.method == 'POST':
        pagination_content = ""
        page_number = request.POST['data[page]'] if request.POST['data[page]'] else 1
        page = int(page_number)
        name = request.POST['data[th_name]']
        sort = '-' if request.POST['data[th_sort]'] == 'DESC' else ''
        search = request.POST['data[search]']
        max = int(request.POST['data[max]'])

        cur_page = page
        page -= 1
        per_page = max  # Set the number of results to display
        start = page * per_page

        # If search keyword is not empty, we include a query for searching
        # the "content" or "name" fields in the database for any matched strings.
        if search:
            all_posts = Product.objects.filter(Q(content__contains=search) | Q(name__contains=search),
                                               author=request.user.id).order_by(sort + name)[start:per_page]
            count = Product.objects.filter(Q(content__contains=search) | Q(name__contains=search),
                                           author=request.user.id).count()

        else:
            all_posts = Product.objects.filter(author=request.user.id).order_by(sort + name)[start:cur_page * max]
            count = Product.objects.filter(author=request.user.id).count()

        if all_posts:
            for post in all_posts:

ecommerce/templates/ecommerce/user/account.html
{% extends "ecommerce/base.html" %}

{% block content %}
	<div class="container wave-box-wrapper">
		<div class="wave-box"></div>
		<form action="{% url 'ecommerce:user_account' %}" method="post" class="update-account">
			{% csrf_token %}
			<div class="col-md-10 offset-md-1">
				<div class="card">
					<div class="card-header">My Account</div>
					<div class="card-body">
						<div class="form-group row">
							<label for="{{ form.username.id_for_label }}" class="col-md-3 control-label text-md-right">Username<span class="text-danger">*</span>:</label>
							<div class="col-md-7">
								{{ form.username }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.email.id_for_label }}" class="col-md-3 control-label text-md-right">Email<span class="text-danger">*</span>:</label>
							<div class="col-md-7">
								{{ form.email }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.old_password.id_for_label }}" class="col-md-3 control-label text-md-right">Old password:</label>
							<div class="col-md-7">
								{{ form.old_password }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.password.id_for_label }}" class="col-md-3 control-label text-md-right">New password:</label>
							<div class="col-md-7">
								{{ form.password }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.password_repeat.id_for_label }}" class="col-md-3 control-label text-md-right">Confirm New password:</label>
							<div class="col-md-7">
								{{ form.password_repeat }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.first_name.id_for_label }}" class="col-md-3 control-label text-md-right">First Name:</label>
							<div class="col-md-7">
								{{ form.first_name }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.last_name.id_for_label }}" class="col-md-3 control-label text-md-right">Last Name:</label>
							<div class="col-md-7">
								{{ form.last_name }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.phone_number.id_for_label }}" class="col-md-3 control-label text-md-right">Phone Number:</label>
							<div class="col-md-7">
								{{ form.phone_number }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.about_me.id_for_label }}" class="col-md-3 control-label text-md-right">About Me:</label>
							<div class="col-md-7">
								{{ form.about_me }}
							</div>
						</div>
						<div class="col-md-7 offset-md-3 px-0 px-xl-2">
							<input type="submit" value="Update" class="btn btn-primary">
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
{% endblock %}

ecommerce/templates/ecommerce/user/login.html
{% extends "ecommerce/base.html" %}
{% load i18n %}
{% block content %}
	<div class="container">
		<form action="{% url 'ecommerce:user_login' %}" method="post">
			{% csrf_token %}
			<div class="col-md-8 offset-md-2">
				<div class="card">
					<div class="card-header">{% trans "Login" %}</div>
					<div class="card-body">
						{% if error_message %}
							<div class="alert alert-danger" role="alert">{{ error_message }}</div>
						{% endif %}
						<div class="form-group row">
							<label for="username" class="col-md-4 control-label text-md-right">{% trans "Username" %}</label>
							<div class="col-md-6">
								<input name="username" value="" type="text" class="form-control" />
							</div>
						</div>
						<div class="form-group row">
							<label for="password" class="col-md-4 control-label text-md-right">{% trans "Password" %}</label>
							<div class="col-md-6">
								<input name="password" type="password" class="form-control" />
							</div>
						</div>
						<div class="col-md-6 offset-md-4 px-0 px-xl-2">
							<input name="login" type="submit" value="{% trans 'login' %}" class="btn btn-primary" /> &nbsp;
							<a href="/ecommerce/user/register">{% trans 'or Register' %}</a>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
{% endblock %}

ecommerce/templates/ecommerce/user/register.html
{% extends "ecommerce/base.html" %}
{% load i18n %}

{% block content %}
	<div class="container wave-box-wrapper">
		<div class="wave-box"></div>
		<form action="{% url 'ecommerce:user_register' %}" method="post" class="create-account">
			{% csrf_token %}
			<div class="col-md-8 offset-md-2">
				<div class="card">
					<div class="card-header">{% trans 'Register' %}</div>
					<div class="card-body">
						<div class="form-group row">
							<label for="{{ form.username.id_for_label }}" class="col-md-4 control-label text-md-right">{% trans "Username" %}<span class="text-red">*</span>:</label>
							<div class="col-md-6">
								{{ form.username }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.email.id_for_label }}" class="col-md-4 control-label text-md-right">{% trans "Email" %}<span class="text-red">*</span>:</label>
							<div class="col-md-6">
								{{ form.email }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.password.id_for_label }}" class="col-md-4 control-label text-md-right">{% trans "Password" %}<span class="text-red">*</span>:</label>
							<div class="col-md-6">
								{{ form.password }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.password_repeat.id_for_label }}" class="col-md-4 control-label text-md-right">{% trans "Confirm Password" %}</label>
							<div class="col-md-6">
								{{ form.password_repeat }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.first_name.id_for_label }}" class="col-md-4 control-label text-md-right">{% trans "First Name" %}</label>
							<div class="col-md-6">
								{{ form.first_name }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.last_name.id_for_label }}" class="col-md-4 control-label text-md-right">{% trans "Last Name" %}</label>
							<div class="col-md-6">
								{{ form.last_name }}
							</div>
						</div>
						<div class="form-group row">
							<label for="{{ form.phone_number.id_for_label }}" class="col-md-4 control-label text-md-right">{% trans "Phone Number" %}</label>
							<div class="col-md-6">
								{{ form.phone_number }}
							</div>
						</div>
						<div class="col-md-6 offset-md-4 px-0 px-xl-2">
							<input type="submit" value="{% trans 'Register' %}" class="btn btn-primary">
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
{% endblock %}